version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: dhl-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: dhl_guias_db
      MYSQL_USER: dhluser
      MYSQL_PASSWORD: dhlpass
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
